//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int IdTask { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime deadline { get; set; }
        public string status { get; set; }
        public int projectId { get; set; }
        public Nullable<int> UserTaskId { get; set; }
    
        public virtual project project { get; set; }
        public virtual user user { get; set; }
    }
}
